version: '2'
services:
    toom-app:
        image: toom
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://toom-mysql:3306/toom?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8090:8090
    toom-mysql:
        extends:
            file: mysql.yml
            service: toom-mysql
